### ISSUE TITLE
How can I fix the clutch axis?

### ISSUE THREAD

**Issue by culebron** [scarburato/t150_driver#19]
Hello everyone,
grazie mille, Dario, sei grandissimo! Lots of thanks to Dario and other contributors! You saved my day.

I got such a wheel recently and it worked well for me, except for clutch pedal. (Model T150 PRO).

In Live For Speed, I see 2 devices: `T150... (event)` and `T150 (js)`. In the first one, clutch duplicates the brake pedal. In the second one, clutch is on the same axis as the steering wheel.

I have a bit of C experience with Arduinos. What can I change to try recompiling it and making clutch axis work independently? I walked through files and can't exactly point at what is changeable. (sorry if I make an issue without a need)

I see t150_input_state_packet, but if it's what the wheel sends, then IDK how to change that, except send it some state packet?

**Comment by scarburato** [comment]
The js device is created by the legacy joystick api, it is preferable to use event. You can test an event device by running `evtest` and selecting the wheel. Are in `evtest` the clutch, brake or steering reported on the same axis? 

> I see t150_input_state_packet, but if it's what the wheel sends, then IDK how to change that, except send it some state packet?

It is the content of the packet received from the wheel. I have the T150 without clutch and gear stick so I guessed where the clutch was and probably I've made the wrong guess 😅.

If the problem is real (not caused by the game) we have to find out where the clutch axis is reported in packet, to do so install Wireshark, load the the `usbmon` kernel module with `modprobe usbmon`, start capture session on `usbmon0` and start moving the clutch pedal then stop the recording. Attach the recording to this discussion. We are looking for packets starting with 07, so you can apply the filter `usb.capdata[0] == 07` and start looking for which bytes change when the clutch position is modified

**Comment by culebron** [comment]
Ok, I did
* install usbmon
* sudo modprobe usbmon
* install wireshark
* sudo wireshark

Here are two capture files on `usbmon0`: one with LFS running, another without it.

https://drive.google.com/file/d/1ucttnsIxm1NY1If8pljLmS7Tx5ai0Tq6/view?usp=sharing
https://drive.google.com/file/d/1Y2GgadQqV6IxpTHKNUBc3aJEqZhuRzZz/view?usp=sharing

**Comment by culebron** [comment]
![Selection_003](https://user-images.githubusercontent.com/119675/113117660-e30c7380-9238-11eb-8c00-0e69a929834a.png)
![Selection_004](https://user-images.githubusercontent.com/119675/113117684-e7389100-9238-11eb-82ae-5d66b8ea0148.png)
![Selection_005](https://user-images.githubusercontent.com/119675/113117691-e869be00-9238-11eb-9758-7dbdb760701d.png)
![Selection_006](https://user-images.githubusercontent.com/119675/113117700-ea338180-9238-11eb-97bf-aa056f968e18.png)

**Comment by culebron** [comment]
Seems to be the same as expected in `input.h`.

But it's not LFS issue, the same happens in Wine controllers setup: 
* "event" device puts brake and clutch on Z, Rz, 
* "js" device puts clutch on X/Y

Is that a problem with just axes indicators? (https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/input-event-codes.h#L824)

![Selection_009](https://user-images.githubusercontent.com/119675/113123451-ce32de80-923e-11eb-958d-d941461f3a31.png)
![Game Controllers_010](https://user-images.githubusercontent.com/119675/113123460-cf640b80-923e-11eb-86d4-f7511a12133c.png)

**Comment by culebron** [comment]
FIXED IT!

* changed ABS_Z to ABS_RUDDER
* make
* sudo rmmod hid-t150.ko
* sudo insmod hid-t150.ko
* dmesg -w
* unplug & plug the wheel
* everything's fine in dmesg
* new axis in LFS!

**Comment by scarburato** [comment]
0k thanks! Can you make a merge request with the change?

Also, if you'd like you can make the same experiment to find the shifter buttons

**Comment by culebron** [comment]
Made a pull request for the pedal. To make it appear in Wine controller tool, I set it to RZ.

**Comment by culebron** [comment]
Checked the buttons, all of them work fine.
